version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region cn-north-1 | docker login --username AWS --password-stdin 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn
  build:
    commands:
      - docker build -t test1 .
      - docker tag test1:latest 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn/test1:latest
  post_build:
    commands:
      - docker push 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn/test1:latest
