version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region cn-north-1 | docker login --username AWS --password-stdin 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn
      - REPOSITORY_URI=189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn/test1
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
