version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t test1:latest .  
      - docker tag test1:latest 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn/test1    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn/test1:latest
