version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region cn-north-1 | docker login --username AWS --password-stdin 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t my-web-app-repository .
      - docker tag my-web-app-repository:latest 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn/my-web-app-repository:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push 189092930338.dkr.ecr.cn-north-1.amazonaws.com.cn/my-web-app-repository:latest
